spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/study?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456
  mail:
    host: smtp.163.com
    protocol: smtps
    username: 18013840405@163.com
    password: VMNZUZDMQWYPIMWU
    port: 465
    properties:
      from: 18013840405@163.com
  data:
    redis:
      database: 0
      host: 127.0.0.1
      port: 6379



